### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by noneissome**
Fixed readme

### CODE REVIEW

**Comment by cmckni3** [comment]
LGTM but I would say 8+. Specifically 8 or 10 to encourage using LTS versions of node.

**Comment by cmckni3** [comment]
Maybe a note somewhere also to say it will work with >= 7.6 but LTS versions of node are recommended.

Thoughts @jamonholmgren?

**Comment by jamonholmgren** [comment]
@cmckni3 I agree with you, although this PR is good to merge now so I will. Maybe @noneissome can do another PR with that.

**Comment by noneissome** [comment]
> @cmckni3 I agree with you, although this PR is good to merge now so I will. Maybe @noneissome can do another PR with that.

Shall do.

**Pull request merged**
