### PR TITLE
Adds home page for docs

### LINKED ISSUE #332: Docs home page 404
image

Looks like we have a md template issue here.

### PR DESCRIPTION
**Pull request by jamonholmgren**
Fixes #332.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@skellock How do we deploy the docs?

**Comment by skellock** [comment]
You don't.  That's why i picked docsify.  ❤️

**Comment by jamonholmgren** [comment]
But ... it didn't work. :( 

image

**Comment by jamonholmgren** [comment]
Oh, does it have to be all caps screaming `README.md` ?

**Comment by jamonholmgren** [comment]
Fixed. 


image

**Pull request merged**
