### PR TITLE
switch out tables

### LINKED ISSUE #207: Switch out ascii-table
Looks like there's a better table lib that would handle colors:

https://github.com/gajus/table

### PR DESCRIPTION
**Pull request by GantMan**
### In this PR
Remove ASCII table and use "Table"

Keep the old table format by default, but allow so much more.

As the name ASCII implies, it sucks at Unicode characters.

Secondly, I wanted to do some advanced table dancing... wait.. wut?

But seriously, I want a Markdown table print option.  So I switched to a configurable table, and configured it.  Added tests for the 3 default modes and kept default behavior the same.

-------
closes #207

### CODE REVIEW

**Comment by GantMan** [comment]
Gotcha. What's the upper bound cost for a swap, should I shop other table creators? Or even construct it myself (it doesn't seem hard honestly).

**Comment by skellock** [comment]
There's no official budget size.  We should aim to keep it down though.

The only reason I'm 👎 on this PR is because we used to bring in the whole `lodash` lib, but it's around 4.5mb.  We only use a handful of functions (the ones around string casing), so I switched them to use their [individual packages](https://github.com/infinitered/gluegun/blob/master/package.json#L45-L59) instead.

`table` would undo that.

I agree with you that our current choice is 💩 tho.

I use [`cli-table2`](https://github.com/jamestalmage/cli-table2) on a different project (app-machine).  It works really well and it's about a quarter of the size. It supports the proper string widths even using colours.

It'd be a good fit and it looks like it supports most of the same things as `table`.  Probably wouldn't make your PR look that much different either.

**Comment by jamonholmgren** [comment]
I like the idea of `cli-table2`, and agree with @skellock that we don't want to pull in large dependencies when we don't have to.

**Comment by skellock** [comment]
@GantMan flipped the tables in #280.  Literally.

**Comment by jamonholmgren** [comment]
table flip

**Pull request closed without merging**
