### PR TITLE
⚡️ Improves Startup Performance, Adds 'gluegun/toolbox' for on-demand loading

### PR DESCRIPTION
**Pull request by jamonholmgren**
Per #355, I decided to add a method to the builder to allow excluding certain core extensions if you don't need them and want to save the startup cost. `print`, `prompt`, `http`, and `system` are the slowest loading.

The API change simply adds this method, like this:

```js
  const cli = build()
    .brand('gluegun')
    .exclude(['semver', 'prompt', 'http', 'patching'])
    .src(__dirname)
    .help()
    .version()
    .create()
```

Additionally, these tools are not available via `require('gluegun')` anymore. However, they are exposed in `require('gluegun/toolbox')`.

```js
const { semver, prompt } = require('gluegun/toolbox')
```

Lastly, this pull request removes Rollup 😢because it no longer makes sense in the context of on-demand loaded resources.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Merging without feedback :shame: ... trying to cut a new release soon, so I'm pushing forward.

**Comment by skellock** [comment]
When I read notifications from my iPad, it marks it as read on github. I then have to remember to search for it from my laptop, or it drops off my radar.  :(

Never hesitate to @skellock me if you think I missed something.  Especially on our open source stuff.

If I don’t respond within 24 hours, send out a search party.

**Comment by skellock** [comment]
I’m cool with this PR.

I find it so weird it takes that long to boot up a few of these libs.  Makes me want to dig in to find out why.

**Comment by jamonholmgren** [comment]
> Makes me want to dig in to find out why.

Same, especially with `print`, because that one is pretty much _always_ necessary. I can understand `prompt` with all the plugins it has to load and whatnot.

**Comment by skellock** [comment]
I wonder if it is the colors lib?  I know they monkeypatch the string prototype.  Perhaps that’s costly?  Perhaps chalk is better?

**Comment by GantMan** [comment]
Jamon this new function is awesome.   When you generate a plugin should it have a commented out line with this in place, and everything listed?  And a comment?


So if I'm new, I generate a new project from your CLI generator, and now there's a friendly line that tells me (a total newb) how to make my startup faster?

**Comment by jamonholmgren** [comment]
@skellock We can avoid monkeypatching string by using `'colors/safe'`.

https://github.com/Marak/colors.js#using-string-safe-api

I think we should make this change. It shouldn't affect any documented API. I'll make an issue.

@GantMan Yes, we should add that. I'll add an issue.

**Comment by GantMan** [comment]
I'm eager to add these features to Solidarity.  When are you cutting a build?

**Comment by GantMan** [comment]
bc Solidarity 2.0 is coming very soon

**Comment by jamonholmgren** [comment]
@GantMan Getting close! Hopefully this week.

**Comment by jamonholmgren** [comment]
@GantMan New Solidarity gluegun update here: https://github.com/infinitered/solidarity/pull/177

**Pull request merged**
