### PR TITLE
Inflection Support

### PR DESCRIPTION
**Pull request by ryanlntn**
This PR adds [pluralize](https://github.com/blakeembrey/pluralize) as a dependency and exposes it's functions under string utils. Adding the following functions:

`plural`
`singular`
`addPluralRule`
`addSingularRule`
`addIrregularRule`
`addUncountableRule`
`isPlural`
`isSingular`

### CODE REVIEW

**Comment by ryanlntn** [comment]
Yeah sure thing.

**Comment by skellock** [comment]
Sweet!  Thanks!

**Comment by ryanlntn** [comment]
btw @skellock the plural of regex is regexen: https://en.wiktionary.org/wiki/regex

Should I fix?

**Comment by jamonholmgren** [comment]
Excellent. We should update the readme too; I'm happy to do that before releasing.

**Pull request merged**
