### PR TITLE
Adds new patching exists and fix runcontext run.

### PR DESCRIPTION
**Pull request by skellock**

### CODE REVIEW

**Comment by skellock** [comment]
The error failing is `npm` related.

Classic `npm`.  Man that 5.x release has been a disaster.

**Comment by skellock** [comment]
@GantMan hit me up with self-merge wolf dude.

**Comment by GantMan** [comment]
image

**Comment by skellock** [comment]
Woah. I didn't expect that.

**Comment by GantMan** [comment]
image

**Pull request merged**
