### PR TITLE
Fix table print bug

### PR DESCRIPTION
**Pull request by GantMan**
Looks like a line of code found it's way in.

No tests provided this round.  We should really do a full pass at some point.

## Before:
image

## After:
image

### CODE REVIEW

**Comment by GantMan** [comment]
Good news is this tripped the snapshot test!  Bad news is, you must have broken this and said "i'm ok with that" to update the snapshot, lol.

Fixing snapshot now.

**Comment by jamonholmgren** [comment]
Hm, I don't think this is entirely correct. We need to look at this section of code closer.

I had some issues with typing the original line. Specifically, the part that shows this:

`[tableArray.options.head, ...tableArray]`

image

Because of that, my assumption was I needed to do this:

```js
[tableArray.options.head, ...tableArray]

// became

[tableArray.options.head].concat(tableArray)
```

Perhaps the `...tableArray` wasn't doing anything before? This part of the code is really confusing to me, and just deleting the `.concat()` without knowing why won't quite cut it.

**Comment by jamonholmgren** [comment]
I also don't remember updating the snapshot at any point during this process.

**Comment by GantMan** [comment]
image

**Pull request merged**
