### PR TITLE
Add closing quote to runtime docs

### PR DESCRIPTION
**Pull request by imranolas**

### CODE REVIEW

**Comment by skellock** [comment]
Oh hey!  You're with Formidable!  🖖

**Comment by imranolas** [comment]
Sure can. I knows javascript 🤦‍♂️

**Comment by skellock** [comment]
💯  Just need to remove that trailing `}` now.  Haha.  💪

**Comment by imranolas** [comment]
Haha. I try and do a nice thing and this is what happens 🙄

**Comment by skellock** [comment]
It was a very nice thing.  Thanks for your time.

Pretty much quitting time over there in London.  Have a great weekend!

**Comment by jamonholmgren** [comment]
@skellock You didn't miss it -- you [pointed it out to me](https://github.com/infinitered/gluegun/pull/223#discussion_r141323543) and I ignored you because I like the interpolated style. ;)

**Pull request merged**
