### PR TITLE
missing type pass along of semver

### PR DESCRIPTION
**Pull request by GantMan**
Merge this one for now, but.....

seems there must be a better way.  Perhaps:
https://github.com/DefinitelyTyped/tsd/blob/master/typings/semver/semver.d.ts

### CODE REVIEW

**Comment by skellock** [comment]
Let's using their typings if they're correct.

**Comment by GantMan** [comment]
Sounds good to me... I have no clue how to do that.

**Comment by GantMan** [comment]
Also, kinda strange that we ever tried to compete eh?

**Pull request merged**
