### PR TITLE
docs(help): Fix help override example

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by skellock** [comment]
Thank you.

**Comment by skellock** [comment]
That CI failure isn't from you.  =)

**Comment by cmckni3** [comment]
No problem. Glad to contribute

**Comment by jamonholmgren** [comment]
@cmckni3 Thanks! looks like there's some sort of conflict? Don't have time to look into it right now myself

**Comment by cmckni3** [comment]
The failure looks like the TypeScript types for `colors` don't match, are wrong, or are missing.

**Comment by jamonholmgren** [comment]
Got it, fixed in next PR

**Pull request merged**
