### PR TITLE
Fix commands parsing issues on Windows

### PR DESCRIPTION
**Pull request by kavengagne**
Hi,
This PR is related to issue #384.

Subcommands are not resolved properly on Windows.

Also added some fixes to get tests to pass on Windows.

### CODE REVIEW

**Comment by kavengagne** [comment]
The CI error was already present in master

**Comment by cmckni3** [comment]
Looks like the cli table upgrade may have broken something in master. I'm investigating that right now.

**Comment by cmckni3** [comment]
Seems to be an npm bug or something strange happening in ci. Tests pass for me locally.

**Comment by kavengagne** [comment]
@cmckni3 We are good to go I guess

**Comment by cmckni3** [comment]
Thanks!

**Comment by jamonholmgren** [comment]
Thank you @kavengagne !

**Pull request merged**
