### PR TITLE
Table swap

### PR DESCRIPTION
**Pull request by GantMan**
For assured acceptance, doing my needed feature in 2 parts.

1. Swap out table provider
2. Add markdown table

This is part 1.  Swap existing table (`ascii-table`) functionality 1 to 1 for `cli-table2`

image
^ Demo of no change of behavior.

AsciiTable has been removed 100%, and all references updated.

### CODE REVIEW

**Comment by GantMan** [comment]
So apparently the test was not telling me what was wrong, it was like diagnosing over the phone.

image

So I did the smart thing and swapped the table test out for a snapshot test.  No more re-creating tables in code just to verify they work.

**Comment by GantMan** [comment]
ok, @skellock - I've shoved the output through a hash function and I can't detect the fail from the message.... what's up with this test?

**Comment by skellock** [comment]
No clue why that's failing.

**Comment by skellock** [comment]
HAHAHAHAHA.  Those commits.

It was terminal colouring was it?

**Pull request merged**
