### PR TITLE
Support async extension setup

### PR DESCRIPTION
**Pull request by RichiCoder1**
Allows an extensions to return a promise on setup to allow for async operations like async FS IO, or remote fetching.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@RichiCoder1 Thank you! Can you add some documentation on how to use this and a test? I would suggest documenting in this file: https://github.com/infinitered/gluegun/blob/0bad0f6fc3f3523f0ed5ca06c570ec2cf36da6c3/docs/plugins.md#extensions

Tests in here: https://github.com/infinitered/gluegun/blob/0bad0f6fc3f3523f0ed5ca06c570ec2cf36da6c3/src/loaders/extension-loader.test.ts

**Comment by RichiCoder1** [comment]
Added tests and docs. Also added a timeout, but I'm half tempted to tear it out. Thoughts?

**Comment by RichiCoder1** [comment]
Pulled it out! Let me know whatcha think

**Comment by jamonholmgren** [comment]
I think we just need some documentation and then we're good to go!

**Comment by RichiCoder1** [comment]
Sorry for the delay on that, I thought I had written docs. Added!

**Pull request merged**
