### PR TITLE
add additional typescript options to cli output

### PR DESCRIPTION
**Pull request by JessWallin**
Addresses #611 

I'm not totally sure this is what you had in mind for this issue, but please let me know! I'm happy to keep working on this until it's the right solution.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Looks great Jess! Thanks so much!

**Comment by jamonholmgren** [comment]
I was a little quick on the trigger, @JessWallin -- we need to make sure the new file gets copied over if it's a TypeScript project.

You can do that by adding it here (in a new PR):

https://github.com/infinitered/gluegun/blob/6ca91b65ced78fea481151db64cdbb0a8e81893c/src/cli/commands/new.ts#L117-L121

**Comment by JessWallin** [comment]
Submitting those changes now, @jamonholmgren

**Comment by jamonholmgren** [comment]
Ref #631 but my fault, not necessary.

**Pull request merged**
