### PR TITLE
Added .defaultCommand and .command to CLI builder

### LINKED ISSUE #276: Command not found should fail more gracefully
Steps to replicate:

Create a command folder structure like this:

image

Then run `mycli logo`. Fails with an error like this:

```
(node:50164) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: Couldn't load command help -- needs a "run" property with a function.
(node:50164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The error is there, but buried in unhandled promise errors.

Here is a good starting point: https://github.com/infinitered/gluegun/blob/master/src/loaders/command-loader.js#L42

### PR DESCRIPTION
**Pull request by jamonholmgren**
Also improved documentation and fixed a couple minor issues. Fixes #276.

This allows you to add arbitrary commands to your CLI:

```js
build()
  .brand('movies')
  .src(__dirname)
  .command({
    name: 'list',
    alias: ['l', 'search'],
    run: context => context.print.info('Listing movies...')
  })
  .command({
    name: 'favorite',
    alias: ['f', 'fav'],
    run: context => context.print.info('Favoriting movies...')
  })
```

Additionally, I've provided a default command which runs when no other command is found:

```js
build()
  .brand('movies')
  .src(__dirname)
  .defaultCommand()
```

image

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Me too ... tiny CLIs could be just one file, now.

**Comment by skellock** [comment]
Almost like `commander`  😊

**Comment by jamonholmgren** [comment]
but better

**Comment by skellock** [comment]
Gloriously creepy.  Well done.

**Pull request merged**
