### PR TITLE
Fix for breaking unit tests on newly created projects

### PR DESCRIPTION
**Pull request by ElonVolo**
Fix for infinitered/gluegun#760.

### CODE REVIEW

**Review by montera82 — APPROVED** [review]
worked for me when i bumped ts-node version as done in this PR.

**Comment by jamonholmgren** [comment]
I'm not sure what the CI failure is here. Don't currently have time to dig into it. Are tests passing locally?

**Comment by rodrigo-picanco** [comment]
Worked for me as well

**Comment by ElonVolo** [comment]
It's not just tests breaking, though. Now, when you create a stock typescript and run it it breaks.

**Comment by ElonVolo** [comment]
@jamonholmgren  Some act of weird gitness stripped the command from the end of a line in package.json. Assuming this passes tests it should be a fix

**Pull request merged**
